defmodule Engine.SystemInfo do
  @moduledoc """
  Provides struct and type for a SystemInfo
  """

  @type t :: %__MODULE__{
          Architecture: String.t() | nil,
          BridgeNfIp6tables: boolean | nil,
          BridgeNfIptables: boolean | nil,
          CDISpecDirs: [String.t()] | nil,
          CPUSet: boolean | nil,
          CPUShares: boolean | nil,
          CgroupDriver: String.t() | nil,
          CgroupVersion: String.t() | nil,
          Containerd: Engine.ContainerdInfo.t() | nil,
          ContainerdCommit: Engine.Commit.t() | nil,
          Containers: integer | nil,
          ContainersPaused: integer | nil,
          ContainersRunning: integer | nil,
          ContainersStopped: integer | nil,
          CpuCfsPeriod: boolean | nil,
          CpuCfsQuota: boolean | nil,
          Debug: boolean | nil,
          DefaultAddressPools: [Engine.SystemInfoDefaultAddressPools.t()] | nil,
          DefaultRuntime: String.t() | nil,
          DockerRootDir: String.t() | nil,
          Driver: String.t() | nil,
          DriverStatus: [[String.t()]] | nil,
          ExperimentalBuild: boolean | nil,
          GenericResources: [Engine.GenericResources.t()] | nil,
          HttpProxy: String.t() | nil,
          HttpsProxy: String.t() | nil,
          ID: String.t() | nil,
          IPv4Forwarding: boolean | nil,
          Images: integer | nil,
          IndexServerAddress: String.t() | nil,
          InitBinary: String.t() | nil,
          InitCommit: Engine.Commit.t() | nil,
          Isolation: String.t() | nil,
          KernelMemoryTCP: boolean | nil,
          KernelVersion: String.t() | nil,
          Labels: [String.t()] | nil,
          LiveRestoreEnabled: boolean | nil,
          LoggingDriver: String.t() | nil,
          MemTotal: integer | nil,
          MemoryLimit: boolean | nil,
          NCPU: integer | nil,
          NEventsListener: integer | nil,
          NFd: integer | nil,
          NGoroutines: integer | nil,
          Name: String.t() | nil,
          NoProxy: String.t() | nil,
          OSType: String.t() | nil,
          OSVersion: String.t() | nil,
          OomKillDisable: boolean | nil,
          OperatingSystem: String.t() | nil,
          PidsLimit: boolean | nil,
          Plugins: Engine.PluginsInfo.t() | nil,
          ProductLicense: String.t() | nil,
          RegistryConfig: Engine.RegistryServiceConfig.t() | nil,
          RuncCommit: Engine.Commit.t() | nil,
          Runtimes: Engine.SystemInfoRuntimes.t() | nil,
          SecurityOptions: [String.t()] | nil,
          ServerVersion: String.t() | nil,
          SwapLimit: boolean | nil,
          Swarm: Engine.SwarmInfo.t() | nil,
          SystemTime: String.t() | nil,
          Warnings: [String.t()] | nil
        }

  defstruct [
    :Architecture,
    :BridgeNfIp6tables,
    :BridgeNfIptables,
    :CDISpecDirs,
    :CPUSet,
    :CPUShares,
    :CgroupDriver,
    :CgroupVersion,
    :Containerd,
    :ContainerdCommit,
    :Containers,
    :ContainersPaused,
    :ContainersRunning,
    :ContainersStopped,
    :CpuCfsPeriod,
    :CpuCfsQuota,
    :Debug,
    :DefaultAddressPools,
    :DefaultRuntime,
    :DockerRootDir,
    :Driver,
    :DriverStatus,
    :ExperimentalBuild,
    :GenericResources,
    :HttpProxy,
    :HttpsProxy,
    :ID,
    :IPv4Forwarding,
    :Images,
    :IndexServerAddress,
    :InitBinary,
    :InitCommit,
    :Isolation,
    :KernelMemoryTCP,
    :KernelVersion,
    :Labels,
    :LiveRestoreEnabled,
    :LoggingDriver,
    :MemTotal,
    :MemoryLimit,
    :NCPU,
    :NEventsListener,
    :NFd,
    :NGoroutines,
    :Name,
    :NoProxy,
    :OSType,
    :OSVersion,
    :OomKillDisable,
    :OperatingSystem,
    :PidsLimit,
    :Plugins,
    :ProductLicense,
    :RegistryConfig,
    :RuncCommit,
    :Runtimes,
    :SecurityOptions,
    :ServerVersion,
    :SwapLimit,
    :Swarm,
    :SystemTime,
    :Warnings
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      Architecture: {:string, :generic},
      BridgeNfIp6tables: :boolean,
      BridgeNfIptables: :boolean,
      CDISpecDirs: [string: :generic],
      CPUSet: :boolean,
      CPUShares: :boolean,
      CgroupDriver: {:enum, ["cgroupfs", "systemd", "none"]},
      CgroupVersion: {:enum, ["1", "2"]},
      Containerd: {Engine.ContainerdInfo, :t},
      ContainerdCommit: {Engine.Commit, :t},
      Containers: :integer,
      ContainersPaused: :integer,
      ContainersRunning: :integer,
      ContainersStopped: :integer,
      CpuCfsPeriod: :boolean,
      CpuCfsQuota: :boolean,
      Debug: :boolean,
      DefaultAddressPools: [{Engine.SystemInfoDefaultAddressPools, :t}],
      DefaultRuntime: {:string, :generic},
      DockerRootDir: {:string, :generic},
      Driver: {:string, :generic},
      DriverStatus: [[string: :generic]],
      ExperimentalBuild: :boolean,
      GenericResources: [{Engine.GenericResources, :t}],
      HttpProxy: {:string, :generic},
      HttpsProxy: {:string, :generic},
      ID: {:string, :generic},
      IPv4Forwarding: :boolean,
      Images: :integer,
      IndexServerAddress: {:string, :generic},
      InitBinary: {:string, :generic},
      InitCommit: {Engine.Commit, :t},
      Isolation: {:enum, ["default", "hyperv", "process"]},
      KernelMemoryTCP: :boolean,
      KernelVersion: {:string, :generic},
      Labels: [string: :generic],
      LiveRestoreEnabled: :boolean,
      LoggingDriver: {:string, :generic},
      MemTotal: :integer,
      MemoryLimit: :boolean,
      NCPU: :integer,
      NEventsListener: :integer,
      NFd: :integer,
      NGoroutines: :integer,
      Name: {:string, :generic},
      NoProxy: {:string, :generic},
      OSType: {:string, :generic},
      OSVersion: {:string, :generic},
      OomKillDisable: :boolean,
      OperatingSystem: {:string, :generic},
      PidsLimit: :boolean,
      Plugins: {Engine.PluginsInfo, :t},
      ProductLicense: {:string, :generic},
      RegistryConfig: {Engine.RegistryServiceConfig, :t},
      RuncCommit: {Engine.Commit, :t},
      Runtimes: {Engine.SystemInfoRuntimes, :t},
      SecurityOptions: [string: :generic],
      ServerVersion: {:string, :generic},
      SwapLimit: :boolean,
      Swarm: {Engine.SwarmInfo, :t},
      SystemTime: {:string, :generic},
      Warnings: [string: :generic]
    ]
  end
end
